CREATE DATABASE IF NOT EXISTS ydc;

USE ydc;

CREATE TABLE IF NOT EXISTS users (
	id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	login VARCHAR(128) CHARACTER SET utf8 COLLATE utf8_bin,
	password VARCHAR(128) CHARACTER SET utf8 COLLATE utf8_bin,
	score BIGINT UNSIGNED,
	game_key VARCHAR(128) CHARACTER SET utf8 COLLATE utf8_bin
);
